spring.config.import=optional:file:.env[.properties]

spring.profiles.active=dev
spring.application.name=MyAuthAPI
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.add-mappings=false

spring.datasource.hikari.connection-timeout=250
spring.datasource.hikari.validation-timeout=250

logging.level.com.myauth=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=WARN
logging.file.name=logs/myauth-app.log

# JWT
api.cors.origins=${FRONTEND_URL}
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=${JWT_EXPIRATION_MS}