spring.application.name=MyAuth API
spring.datasource.url=jdbc:postgresql://localhost:5431/postgres
spring.datasource.username=postgres
spring.datasource.password=root
debug=false
trace=false
spring.output.ansi.enabled=always
logging.file.path=logs/
logging.file.name=logs/application.log
# JWT Configuration
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000