name: Continuous Integration (dev)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  Unit and Integration Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d testdb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build (skip tests)
        run: mvn clean package -DskipTests

      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -U test -d testdb
            if [ $? -eq 0 ]; then
              echo "Postgres is ready!"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 3
          done

      - name: Run unit & integration tests
        run: mvn clean verify -Dmaven.compiler.failOnWarning=false
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          JWT_SECRET: testkey