name: Continuos Integration(dev)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  dev-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Unit & Integration Tests
        run: mvn clean verify -Dmaven.compiler.failOnWarning=false

      - name: Check docker-compose up
        run: docker compose -f docker-compose.yml up -d --build

      - name: Waiting for containers
        run: sleep 10

      - name: Check if container is running
        run: docker ps

      - name: Cleanup containers
        run: docker compose -f docker-compose.yml down